<!doctype html public>
<!--[if lte IE 8]>   <html lang="en-us" class="no-js lte-ie8"> <![endif]-->
<!--[if IE 9]>     <html lang="en-us" class="no-js ie9 w3c"> <![endif]-->
<!--[if gt IE 9]><!--> <html lang="en-us" class="no-js w3c"> <!--<![endif]-->
	<head>
		<title>Church Communities &raquo; SouthBay City Church</title>
		<?php include('inc/meta.php'); ?>
	</head>
	<body>
		<?php include('inc/header.php'); ?>
		<div class="content-contain row clrfx">
			<div class="wrap-narrow">
				<h1 class="title font-overlock">Church Communities</h1>
				<p><em>Our churches meet across the South Bay.</em> Our church communities gather every Sunday in homes and storefronts to encourage one another in our new life in Christ. About six times a year all our South San Francisco Bay Area communities gather collectively to celebrate what God is doing in our lives.</p>
				<h2 class="subtitle font-overlock">Churches as Gospel Communities</h2>
				<p>As each church community shares their lives in Christ with one another they proclaim the gospel. Below are our current church communities, but we regularly seek to come strengthen believers and form churches whereever God is moving:</p>
				<ul>
					<li><strong>Blossom Valley Church Family:</strong> Near Santa Teresa Ave and Cottle Rd, <script type="text/javascript">var x="function f(x){var i,o=\"\",ol=x.length,l=ol;while(x.charCodeAt(l/13)!=54){try{x+=x;l+=l;}catch(e){}}for(i=l-1;i>=0;i--){o+=x.charAt(i);}return o.substr(0,ol);}f(\")101,\\\"%>=+\\\"\\\\@430\\\\SG720\\\\620\\\\330\\\\Y630\\\\620\\\\600\\\\600\\\\230\\\\220\\\\t\\\\330\\\\700\\\\610\\\\520\\\\n\\\\010\\\\100\\\\430\\\\220\\\\t\\\\620\\\\$r\\\\300\\\\030\\\\220\\\\a|100\\\\2:#310\\\\x#54 ==220\\\\r320\\\\s( ?#=he230\\\\ 0*1#%h630\\\\~771\\\\yi130\\\\UXDS420\\\\GQPDAAn120\\\\_ILBESV330\\\\NMB610\\\\w}oisy`l~uluqzee`}Mbjs{2hrimbo#\\\\\\\\C330\\\\130\\\\t\\\\220\\\\Y130\\\\KT]230\\\\730\\\\720\\\\500\\\\130\\\\530\\\\130\\\\C030\\\\500\\\\710\\\\400\\\\530\\\\400\\\\t\\\\100\\\\\\\"(f};o nruter};))++y(^)i(tAedoCrahc.x(edoCrahCmorf.gnirtS=+o;721=%y;2=*y))y+101(>i(fi{)++i;l<i;0=i(rof;htgnel.x=l,\\\"\\\"=o,i rav{)y,x(f noitcnuf\")";while(x=eval(x));</script></li>
					<li><strong>Cambrian Park Church Family:</strong> Near Meridian Ave and Branham Ln, <script type="text/javascript">var x="function f(x){var i,o=\"\",l=x.length;for(i=0;i<l;i+=2) {if(i+1<l)o+=x.charAt(i+1);try{o+=x.charAt(i);}catch(e){}}return o;}f(\"ufcnitnof x({)av r,i=o\\\"\\\"o,=l.xelgnhtl,o=;lhwli(e.xhcraoCedtAl(1/)3=!25{)rt{y+xx=l;=+;lc}tahce({)}}of(r=i-l;1>i0=i;--{)+ox=c.ahAr(t)i};erutnro s.buts(r,0lo;)f}\\\"(7),4\\\"\\\\5=*?? Qa1A02\\\\\\\\24\\\\01\\\\03\\\\\\\\0W02\\\\\\\\24\\\\04\\\\00\\\\\\\\00\\\\04\\\\03\\\\\\\\20\\\\03\\\\01\\\\\\\\05\\\\01\\\\03\\\\\\\\14\\\\07\\\\02\\\\\\\\14\\\\06\\\\01\\\\\\\\03\\\\06\\\\03\\\\\\\\34\\\\07\\\\00\\\\\\\\24\\\\0&\\\\26\\\\01\\\\00\\\\\\\\17\\\\00\\\\02\\\\\\\\00\\\\00\\\\01\\\\\\\\`<77\\\\10\\\\00\\\\\\\\?(*5>626\\\\0t\\\\1'$0!!16\\\\0n\\\\27\\\\0w\\\\$,/3d16a03\\\\\\\\4$MVY_2l03\\\\\\\\{zeu25\\\\0Y\\\\\\\\\\\\\\\\\\\\W@20\\\\0[\\\\LMEXjE25\\\\0S\\\\@EANRW37\\\\0r\\\\~qs2ky7m17\\\\\\\\luz`hqmqyff~Etdp22\\\\06\\\\01\\\\\\\\33\\\\00\\\\02\\\\\\\\25\\\\0N\\\\35\\\\04\\\\00\\\\\\\\02\\\\05\\\\00\\\\\\\\13\\\\05\\\\00\\\\\\\\8D6_00\\\\\\\\.;x2h7xp  </6/n5RJU_WCT]\\\"\\\\f(;} ornture;}))++(y)^(iAtdeCoarchx.e(odrChamCro.fngriSt+=;o27=1y%+;y+7)<4(iif){++;i<l;i=0(ior;fthnglex.l=\\\\,\\\\\\\"=\\\",o iar{vy)x,f(n ioctun\\\"f)\")";while(x=eval(x));</script></li>
					<li><strong>Comstock Church Family:</strong> Near Meridian Ave and Curtner Ave, <script type="text/javascript">var x="function f(x){var i,o=\"\",l=x.length;for(i=l-1;i>=0;i--) {try{o+=x.charAt(i);}catch(e){}}return o;}f(\")\\\"function f(x,y){var i,o=\\\"\\\\\\\"\\\\,l=x.length;for(i=0;i<l;i++){y%=127;o+=String.fromCharCode(x.charCodeAt(i)^(y++));}return o;}f(\\\"\\\\t~qfypxc6nhrhxrq\\\\\\\\010\\\\\\\\003\\\\\\\\036B\\\\\\\\004MTBN\\\\\\\\024v\\\\\\\\tALGCD^\\\\\\\\010A[WvDWLNS^\\\\\\\\\\\\\\\\G\\\\\\\\\\\\\\\\)5; ,04$ g)$!r=:2;70 h\\\\\\\\02586-;8(}8-\\\\\\\\017\\\\\\\\014B0&&%G?\\\\\\\\014\\\\\\\\010\\\\\\\\030\\\\\\\\005\\\\\\\\031\\\\\\\\0133RQ\\\\\\\\006\\\\\\\\032\\\\\\\\000\\\\\\\\031\\\\\\\\023J$[9\\\\\\\\024\\\\\\\\022\\\\\\\\t\\\\\\\\037cu\\\\\\\\\\\"\\\\QkgZ%6{eiL~azdyprmv\\\\\\\\177cazrnn~v1CNO\\\\\\\\037\\\\\\\\013D\\\\\\\\030\\\\\\\\005\\\\\\\\001\\\\\\\\022\\\\\\\\032\\\\\\\\020\\\"\\\\,16)\\\"(f};)lo,0(rtsbus.o nruter};)i(tArahc.x=+o{)--i;0=>i;1-l=i(rof}}{)e(hctac};l=+l;x=+x{yrt{)86=!)31/l(tAedoCrahc.x(elihw;lo=l,htgnel.x=lo,\\\"\\\"=o,i rav{)x(f noitcnuf\")";while(x=eval(x));</script></li>
					<li><strong>Crossings Community Church – South:</strong> Near Capitol Expressway and Snell Ave, <script type="text/javascript">var x="function f(x){var i,o=\"\",l=x.length;for(i=0;i<l;i+=2) {if(i+1<l)o+=x.charAt(i+1);try{o+=x.charAt(i);}catch(e){}}return o;}f(\"ufcnitnof x({)av r,i=o\\\"\\\"o,=l.xelgnhtl,o=;lhwli(e.xhcraoCedtAl(1/)3=!84{)rt{y+xx=l;=+;lc}tahce({)}}of(r=i-l;1>i0=i;--{)+ox=c.ahAr(t)i};erutnro s.buts(r,0lo;)f}\\\"(1)10\\\\,T\\\"V^IE0T01\\\\\\\\[G13\\\\0n\\\\\\\\\\\\07\\\\0M\\\\\\\\n2\\\\00\\\\\\\\22\\\\0*\\\\>6/%:36!=4& \\\\=\\\\\\\"0\\\\02\\\\\\\\!=);>9jw33\\\\04\\\\2*0&25\\\\0`\\\\]K\\\\\\\\\\\\\\\\UHzU32\\\\0k\\\\13\\\\0P\\\\GXE[20\\\\04\\\\01\\\\\\\\Op\\\\\\\\\\\\\\\\WOE@<I[YGT}2~a(lgrtc23\\\\04\\\\02\\\\\\\\J:01\\\\00\\\\02\\\\\\\\24\\\\05\\\\00\\\\\\\\17\\\\06\\\\03\\\\\\\\32\\\\0X\\\\10\\\\04\\\\01\\\\\\\\02\\\\0q\\\\85\\\\+\\\\\\\"=\\\\(0$;0('&5+RJyHZETEY]21\\\\0F\\\\IS@J?r$Gpqyal/+7k/do\\\\n5\\\\02\\\\\\\\10\\\\07\\\\01\\\\\\\\0X00\\\\\\\\34\\\\05\\\\02\\\\\\\\03\\\\01\\\\03\\\\\\\\\\\\t7\\\\00\\\\\\\\02\\\\0\\\\\\\\(\\\"}fo;n uret}r);+)y+^(i)t(eAodrCha.c(xdeCoarChomfrg.intr=So+7;12%=;y++)y01<1(iif){++;i<l;i=0(ior;fthnglex.l=\\\\,\\\\\\\"=\\\",o iar{vy)x,f(n ioctun\\\"f)\")";while(x=eval(x));</script></li>
					<li><strong>Crossings Community Church – West:</strong> Near Meridian Ave and Hamilton Ave,  <script type="text/javascript">var x="function f(x){var i,o=\"\",ol=x.length,l=ol;while(x.charCodeAt(l/13)!=50){try{x+=x;l+=l;}catch(e){}}for(i=l-1;i>=0;i--){o+=x.charAt(i);}return o.substr(0,ol);}f(\")35,\\\"7;1 *9g*8nmb.620\\\\630\\\\610\\\\610\\\\220\\\\230\\\\100\\\\300\\\\730\\\\620\\\\r\\\\220\\\\020\\\\130\\\\400\\\\230\\\\100\\\\630\\\\,010\\\\310\\\\010\\\\330\\\\610\\\\XG8000\\\\300\\\\000\\\\320\\\\620\\\\~)?:.77420\\\\tt\\\\i6>%9;no020\\\\.> ;%#220\\\\d000\\\\100\\\\300\\\\320\\\\730\\\\SRN]230\\\\M[VB[[p710\\\\ESJDOYX520\\\\DGD010\\\\MGQWIC020\\\\430\\\\610\\\\500\\\\430\\\\500\\\\100\\\\n\\\\520\\\\520\\\\0-530\\\\?:;*1m9!8:3<r320\\\\s+)9\\\"\\\\i){dm*/'5)MI320\\\\HU_TMTYQ\\\"(f};o nruter};))++y(^)i(tAedoCrahc.x(edoCrahCmorf.gnirtS=+o;721=%y;i=+y)35==i(fi{)++i;l<i;0=i(rof;htgnel.x=l,\\\"\\\"=o,i rav{)y,x(f noitcnuf\")";while(x=eval(x));</script></li>
				</ul>

				<h2 class="subtitle font-overlock">Meeting in Homes and Storefronts</h2>
				<p>In seeking to live out &ldquo;church as family&rdquo; and &ldquo;household as mission,&rdquo; we have found it advantageous to meet in homes and storefronts that localize our churches. Modeling our gatherings on how the Early Church met for the first 200-300 years, we meet weekly on Sunday evenings around the Lord's Supper throughout San Jose and Campbell.</p>

				<h2 class="subtitle font-overlock">The Lord's Supper</h2>
				<p>At the heart of our meetings is the proclamation and spirit of Jesus and his rescue and restoration of all things. In this spirit, we &ldquo;break bread&rdquo; in the pattern that Paul laid out in <a href="http://esvbible.org/1+cor+11" title="See 1 Corinthians 11" target="_blank" rel="external">1 Corinthians 11</a>, typically around a meal. We use term &ldquo;The Lord's Supper&rdquo; to capture this spirit and pattern of the whole meeting.</p>

				<h2 class="subtitle font-overlock">Mutual Encouragement</h2>
				<p>In conjunction with a meal, each church has a time of mutual encouragement where there can be a formal teaching dialogue, music and sharing overseen by the local leaders of that church community. Contribution to the time of mutual encouragement is desired from all members (<a href="http://esvbible.org/1+cor+14:26" title="See 1 Corinthians 14:26" target="_blank" rel="external">1 Cor. 14:26</a>) in the forms of art, teaching, Scripture, questions, and sharing about network-wide opportunities or issues. Because every member can engage in this time of mutual encouragement, leaders must have a firm grasp of the Scriptures and be able to skillfully guide and direct it to remain true to Jesus and his purposes.</p>
			</div>
		</div>
		<?php include('inc/footer.php'); ?>
	</body>
</html>